#H2 DB
spring.datasource.url=jdbc:h2:mem:microserviceDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# ===============================
# Eureka Instance Configuration
# ===============================
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.non-secure-port=${server.port}
eureka.instance.instance-id=${spring.application.name}:${server.port}


# ===============================
# Eureka Client Configuration
# ===============================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/eureka/
